package com.android.systemui.statusbar.policy;

import com.android.systemui.R;
import com.android.systemui.statusbar.policy.NetworkControllerImpl;

class TelephonyIcons {
    static final int[][] TELEPHONY_SIGNAL_STRENGTH = {new int[]{R.drawable.stat_sys_signal_0, R.drawable.stat_sys_signal_1, R.drawable.stat_sys_signal_2, R.drawable.stat_sys_signal_3, R.drawable.stat_sys_signal_4}, new int[]{R.drawable.stat_sys_signal_0_fully, R.drawable.stat_sys_signal_1_fully, R.drawable.stat_sys_signal_2_fully, R.drawable.stat_sys_signal_3_fully, R.drawable.stat_sys_signal_4_fully}};
    static final int[][] QS_TELEPHONY_SIGNAL_STRENGTH = {new int[]{R.drawable.ic_qs_signal_0, R.drawable.ic_qs_signal_1, R.drawable.ic_qs_signal_2, R.drawable.ic_qs_signal_3, R.drawable.ic_qs_signal_4}, new int[]{R.drawable.ic_qs_signal_full_0, R.drawable.ic_qs_signal_full_1, R.drawable.ic_qs_signal_full_2, R.drawable.ic_qs_signal_full_3, R.drawable.ic_qs_signal_full_4}};
    static final int[][] TELEPHONY_SIGNAL_STRENGTH_ROAMING = {new int[]{R.drawable.stat_sys_signal_0, R.drawable.stat_sys_signal_1, R.drawable.stat_sys_signal_2, R.drawable.stat_sys_signal_3, R.drawable.stat_sys_signal_4}, new int[]{R.drawable.stat_sys_signal_0_fully, R.drawable.stat_sys_signal_1_fully, R.drawable.stat_sys_signal_2_fully, R.drawable.stat_sys_signal_3_fully, R.drawable.stat_sys_signal_4_fully}};
    static final int[] QS_DATA_R = {R.drawable.ic_qs_signal_r, R.drawable.ic_qs_signal_r};
    static final int[][] DATA_G = {new int[]{R.drawable.stat_sys_data_fully_connected_g, R.drawable.stat_sys_data_fully_connected_g, R.drawable.stat_sys_data_fully_connected_g, R.drawable.stat_sys_data_fully_connected_g}, new int[]{R.drawable.stat_sys_data_fully_connected_g, R.drawable.stat_sys_data_fully_connected_g, R.drawable.stat_sys_data_fully_connected_g, R.drawable.stat_sys_data_fully_connected_g}};
    static final int[] QS_DATA_G = {R.drawable.ic_qs_signal_g, R.drawable.ic_qs_signal_g};
    static final int[][] DATA_3G = {new int[]{R.drawable.stat_sys_data_fully_connected_3g, R.drawable.stat_sys_data_fully_connected_3g, R.drawable.stat_sys_data_fully_connected_3g, R.drawable.stat_sys_data_fully_connected_3g}, new int[]{R.drawable.stat_sys_data_fully_connected_3g, R.drawable.stat_sys_data_fully_connected_3g, R.drawable.stat_sys_data_fully_connected_3g, R.drawable.stat_sys_data_fully_connected_3g}};
    static final int[] QS_DATA_3G = {R.drawable.ic_qs_signal_3g, R.drawable.ic_qs_signal_3g};
    static final int[][] DATA_E = {new int[]{R.drawable.stat_sys_data_fully_connected_e, R.drawable.stat_sys_data_fully_connected_e, R.drawable.stat_sys_data_fully_connected_e, R.drawable.stat_sys_data_fully_connected_e}, new int[]{R.drawable.stat_sys_data_fully_connected_e, R.drawable.stat_sys_data_fully_connected_e, R.drawable.stat_sys_data_fully_connected_e, R.drawable.stat_sys_data_fully_connected_e}};
    static final int[] QS_DATA_E = {R.drawable.ic_qs_signal_e, R.drawable.ic_qs_signal_e};
    static final int[][] DATA_H = {new int[]{R.drawable.stat_sys_data_fully_connected_h, R.drawable.stat_sys_data_fully_connected_h, R.drawable.stat_sys_data_fully_connected_h, R.drawable.stat_sys_data_fully_connected_h}, new int[]{R.drawable.stat_sys_data_fully_connected_h, R.drawable.stat_sys_data_fully_connected_h, R.drawable.stat_sys_data_fully_connected_h, R.drawable.stat_sys_data_fully_connected_h}};
    static final int[] QS_DATA_H = {R.drawable.ic_qs_signal_h, R.drawable.ic_qs_signal_h};
    static final int[][] DATA_HP = {new int[]{R.drawable.stat_sys_data_connected_hp, R.drawable.stat_sys_data_connected_hp, R.drawable.stat_sys_data_connected_hp, R.drawable.stat_sys_data_connected_hp}, new int[]{R.drawable.stat_sys_data_fully_connected_hp, R.drawable.stat_sys_data_fully_connected_hp, R.drawable.stat_sys_data_fully_connected_hp, R.drawable.stat_sys_data_fully_connected_hp}};
    static final int[] QS_DATA_HP = {R.drawable.ic_qs_signal_h, R.drawable.ic_qs_signal_h};
    static final int[][] DATA_1X = {new int[]{R.drawable.stat_sys_data_fully_connected_1x, R.drawable.stat_sys_data_fully_connected_1x, R.drawable.stat_sys_data_fully_connected_1x, R.drawable.stat_sys_data_fully_connected_1x}, new int[]{R.drawable.stat_sys_data_fully_connected_1x, R.drawable.stat_sys_data_fully_connected_1x, R.drawable.stat_sys_data_fully_connected_1x, R.drawable.stat_sys_data_fully_connected_1x}};
    static final int[] QS_DATA_1X = {R.drawable.ic_qs_signal_1x, R.drawable.ic_qs_signal_1x};
    static final int[][] DATA_4G = {new int[]{R.drawable.stat_sys_data_fully_connected_4g, R.drawable.stat_sys_data_fully_connected_4g, R.drawable.stat_sys_data_fully_connected_4g, R.drawable.stat_sys_data_fully_connected_4g}, new int[]{R.drawable.stat_sys_data_fully_connected_4g, R.drawable.stat_sys_data_fully_connected_4g, R.drawable.stat_sys_data_fully_connected_4g, R.drawable.stat_sys_data_fully_connected_4g}};
    static final int[] QS_DATA_4G = {R.drawable.ic_qs_signal_4g, R.drawable.ic_qs_signal_4g};
    static final int[][] DATA_LTE = {new int[]{R.drawable.stat_sys_data_fully_connected_lte, R.drawable.stat_sys_data_fully_connected_lte, R.drawable.stat_sys_data_fully_connected_lte, R.drawable.stat_sys_data_fully_connected_lte}, new int[]{R.drawable.stat_sys_data_fully_connected_lte, R.drawable.stat_sys_data_fully_connected_lte, R.drawable.stat_sys_data_fully_connected_lte, R.drawable.stat_sys_data_fully_connected_lte}};
    static final int[] QS_DATA_LTE = {R.drawable.ic_qs_signal_lte, R.drawable.ic_qs_signal_lte};
    static final NetworkControllerImpl.MobileSignalController.MobileIconGroup THREE_G = new NetworkControllerImpl.MobileSignalController.MobileIconGroup("3G", TELEPHONY_SIGNAL_STRENGTH, QS_TELEPHONY_SIGNAL_STRENGTH, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, R.drawable.stat_sys_signal_null, R.drawable.ic_qs_signal_no_signal, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], R.string.accessibility_data_connection_3g, R.drawable.stat_sys_data_fully_connected_3g, true, QS_DATA_3G);
    static final NetworkControllerImpl.MobileSignalController.MobileIconGroup UNKNOWN = new NetworkControllerImpl.MobileSignalController.MobileIconGroup("Unknown", TELEPHONY_SIGNAL_STRENGTH, QS_TELEPHONY_SIGNAL_STRENGTH, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, R.drawable.stat_sys_signal_null, R.drawable.ic_qs_signal_no_signal, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], 0, 0, false, new int[2]);
    static final NetworkControllerImpl.MobileSignalController.MobileIconGroup E = new NetworkControllerImpl.MobileSignalController.MobileIconGroup("E", TELEPHONY_SIGNAL_STRENGTH, QS_TELEPHONY_SIGNAL_STRENGTH, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, R.drawable.stat_sys_signal_null, R.drawable.ic_qs_signal_no_signal, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], R.string.accessibility_data_connection_edge, R.drawable.stat_sys_data_fully_connected_e, false, QS_DATA_E);
    static final NetworkControllerImpl.MobileSignalController.MobileIconGroup ONE_X = new NetworkControllerImpl.MobileSignalController.MobileIconGroup("1X", TELEPHONY_SIGNAL_STRENGTH, QS_TELEPHONY_SIGNAL_STRENGTH, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, R.drawable.stat_sys_signal_null, R.drawable.ic_qs_signal_no_signal, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], R.string.accessibility_data_connection_cdma, R.drawable.stat_sys_data_fully_connected_1x, true, QS_DATA_1X);
    static final NetworkControllerImpl.MobileSignalController.MobileIconGroup G = new NetworkControllerImpl.MobileSignalController.MobileIconGroup("G", TELEPHONY_SIGNAL_STRENGTH, QS_TELEPHONY_SIGNAL_STRENGTH, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, R.drawable.stat_sys_signal_null, R.drawable.ic_qs_signal_no_signal, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], R.string.accessibility_data_connection_gprs, R.drawable.stat_sys_data_fully_connected_g, false, QS_DATA_G);
    static final NetworkControllerImpl.MobileSignalController.MobileIconGroup H = new NetworkControllerImpl.MobileSignalController.MobileIconGroup("H", TELEPHONY_SIGNAL_STRENGTH, QS_TELEPHONY_SIGNAL_STRENGTH, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, R.drawable.stat_sys_signal_null, R.drawable.ic_qs_signal_no_signal, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], R.string.accessibility_data_connection_3_5g, R.drawable.stat_sys_data_fully_connected_h, false, QS_DATA_H);
    static final NetworkControllerImpl.MobileSignalController.MobileIconGroup HP = new NetworkControllerImpl.MobileSignalController.MobileIconGroup("H+", TELEPHONY_SIGNAL_STRENGTH, QS_TELEPHONY_SIGNAL_STRENGTH, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, R.drawable.stat_sys_signal_null, R.drawable.ic_qs_signal_no_signal, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], R.string.accessibility_data_connection_3_5g, R.drawable.stat_sys_data_fully_connected_hp, false, QS_DATA_HP);
    static final NetworkControllerImpl.MobileSignalController.MobileIconGroup FOUR_G = new NetworkControllerImpl.MobileSignalController.MobileIconGroup("4G", TELEPHONY_SIGNAL_STRENGTH, QS_TELEPHONY_SIGNAL_STRENGTH, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, R.drawable.stat_sys_signal_null, R.drawable.ic_qs_signal_no_signal, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], R.string.accessibility_data_connection_4g, R.drawable.stat_sys_data_fully_connected_4g, true, QS_DATA_4G);
    static final NetworkControllerImpl.MobileSignalController.MobileIconGroup LTE = new NetworkControllerImpl.MobileSignalController.MobileIconGroup("LTE", TELEPHONY_SIGNAL_STRENGTH, QS_TELEPHONY_SIGNAL_STRENGTH, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, R.drawable.stat_sys_signal_null, R.drawable.ic_qs_signal_no_signal, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], R.string.accessibility_data_connection_lte, R.drawable.stat_sys_data_fully_connected_lte, true, QS_DATA_LTE);
    static final NetworkControllerImpl.MobileSignalController.MobileIconGroup ROAMING = new NetworkControllerImpl.MobileSignalController.MobileIconGroup("Roaming", TELEPHONY_SIGNAL_STRENGTH_ROAMING, QS_TELEPHONY_SIGNAL_STRENGTH, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, R.drawable.stat_sys_signal_null, R.drawable.ic_qs_signal_no_signal, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], R.string.accessibility_data_connection_roaming, R.drawable.stat_sys_data_fully_connected_roam, false, QS_DATA_R);
}
