package com.android.server.am;

class ActivityManagerDebugConfig {
    static final boolean APPEND_CATEGORY_NAME = false;
    static boolean DEBUG_ADD_REMOVE = false;
    static boolean DEBUG_ALL = false;
    static boolean DEBUG_ALL_ACTIVITIES = false;
    static boolean DEBUG_ANR = false;
    static boolean DEBUG_APP = false;
    static boolean DEBUG_BACKUP = false;
    static boolean DEBUG_BROADCAST = false;
    static boolean DEBUG_BROADCAST_BACKGROUND = false;
    static boolean DEBUG_BROADCAST_LIGHT = false;
    static boolean DEBUG_CLEANUP = false;
    static boolean DEBUG_CONFIGURATION = false;
    static boolean DEBUG_CONTAINERS = false;
    static boolean DEBUG_FOCUS = false;
    static boolean DEBUG_IDLE = false;
    static boolean DEBUG_IMMERSIVE = false;
    static boolean DEBUG_LOCKSCREEN = false;
    static boolean DEBUG_LOCKTASK = false;
    static boolean DEBUG_LRU = false;
    static boolean DEBUG_MU = false;
    static boolean DEBUG_MULTIWINDOW = false;
    static boolean DEBUG_OOM_ADJ = false;
    static boolean DEBUG_PAUSE = false;
    static boolean DEBUG_PERMISSION = false;
    static boolean DEBUG_PERMISSIONS_REVIEW = false;
    static boolean DEBUG_POWER = false;
    static boolean DEBUG_POWER_QUICK = false;
    static boolean DEBUG_PROCESSES = false;
    static boolean DEBUG_PROCESS_OBSERVERS = false;
    static boolean DEBUG_PROVIDER = false;
    static boolean DEBUG_PSS = false;
    static boolean DEBUG_RECENTS = false;
    static boolean DEBUG_RELEASE = false;
    static boolean DEBUG_RESULTS = false;
    static boolean DEBUG_SAVED_STATE = false;
    static boolean DEBUG_SCREENSHOTS = false;
    static boolean DEBUG_SERVICE = false;
    static boolean DEBUG_SERVICE_EXECUTING = false;
    static boolean DEBUG_STACK = false;
    static boolean DEBUG_STATES = false;
    static boolean DEBUG_SWITCH = false;
    static boolean DEBUG_TASKS = false;
    static boolean DEBUG_TASK_RETURNTO = false;
    static boolean DEBUG_THUMBNAILS = false;
    static boolean DEBUG_TRANSITION = false;
    static boolean DEBUG_UID_OBSERVERS = false;
    static boolean DEBUG_URI_PERMISSION = false;
    static boolean DEBUG_USAGE_STATS = false;
    static boolean DEBUG_USER_LEAVING = false;
    static boolean DEBUG_VISIBILITY = false;
    static boolean DEBUG_VISIBLE_BEHIND = false;
    static boolean DEBUG_WHITELISTS = false;
    static final String POSTFIX_ADD_REMOVE;
    static final String POSTFIX_APP;
    static final String POSTFIX_BACKUP;
    static final String POSTFIX_BROADCAST;
    static final String POSTFIX_CLEANUP;
    static final String POSTFIX_CONFIGURATION;
    static final String POSTFIX_CONTAINERS;
    static final String POSTFIX_FOCUS;
    static final String POSTFIX_IDLE;
    static final String POSTFIX_IMMERSIVE;
    static final String POSTFIX_LOCKSCREEN;
    static final String POSTFIX_LOCKTASK;
    static final String POSTFIX_LRU;
    static final String POSTFIX_MU = "_MU";
    static final String POSTFIX_OOM_ADJ;
    static final String POSTFIX_PAUSE;
    static final String POSTFIX_POWER;
    static final String POSTFIX_PROCESSES;
    static final String POSTFIX_PROCESS_OBSERVERS;
    static final String POSTFIX_PROVIDER;
    static final String POSTFIX_PSS;
    static final String POSTFIX_RECENTS;
    static final String POSTFIX_RELEASE;
    static final String POSTFIX_RESULTS;
    static final String POSTFIX_SAVED_STATE;
    static final String POSTFIX_SCREENSHOTS;
    static final String POSTFIX_SERVICE;
    static final String POSTFIX_SERVICE_EXECUTING;
    static final String POSTFIX_STACK;
    static final String POSTFIX_STATES;
    static final String POSTFIX_SWITCH;
    static final String POSTFIX_TASKS;
    static final String POSTFIX_THUMBNAILS;
    static final String POSTFIX_TRANSITION;
    static final String POSTFIX_UID_OBSERVERS;
    static final String POSTFIX_URI_PERMISSION;
    static final String POSTFIX_USER_LEAVING;
    static final String POSTFIX_VISIBILITY;
    static final String POSTFIX_VISIBLE_BEHIND;
    static final String TAG_AM = "ActivityManager";
    static final boolean TAG_WITH_CLASS_NAME = false;

    ActivityManagerDebugConfig() {
    }

    static {
        DEBUG_ALL_ACTIVITIES = DEBUG_ALL;
        DEBUG_ADD_REMOVE = DEBUG_ALL_ACTIVITIES;
        DEBUG_ANR = false;
        DEBUG_APP = DEBUG_ALL_ACTIVITIES;
        DEBUG_BACKUP = DEBUG_ALL;
        DEBUG_BROADCAST = DEBUG_ALL;
        DEBUG_BROADCAST_BACKGROUND = DEBUG_BROADCAST;
        DEBUG_BROADCAST_LIGHT = DEBUG_BROADCAST;
        DEBUG_CLEANUP = DEBUG_ALL;
        DEBUG_CONFIGURATION = DEBUG_ALL;
        DEBUG_CONTAINERS = DEBUG_ALL_ACTIVITIES;
        DEBUG_FOCUS = false;
        DEBUG_IDLE = DEBUG_ALL_ACTIVITIES;
        DEBUG_IMMERSIVE = DEBUG_ALL;
        DEBUG_LOCKSCREEN = DEBUG_ALL;
        DEBUG_LOCKTASK = DEBUG_ALL;
        DEBUG_LRU = DEBUG_ALL;
        DEBUG_MU = DEBUG_ALL;
        DEBUG_OOM_ADJ = DEBUG_ALL;
        DEBUG_PAUSE = DEBUG_ALL;
        DEBUG_POWER = DEBUG_ALL;
        DEBUG_POWER_QUICK = DEBUG_POWER;
        DEBUG_PROCESS_OBSERVERS = DEBUG_ALL;
        DEBUG_PROCESSES = DEBUG_ALL;
        DEBUG_PROVIDER = DEBUG_ALL;
        DEBUG_PSS = DEBUG_ALL;
        DEBUG_RECENTS = DEBUG_ALL;
        DEBUG_RELEASE = DEBUG_ALL_ACTIVITIES;
        DEBUG_RESULTS = DEBUG_ALL;
        DEBUG_SAVED_STATE = DEBUG_ALL_ACTIVITIES;
        DEBUG_SCREENSHOTS = DEBUG_ALL_ACTIVITIES;
        DEBUG_SERVICE = DEBUG_ALL;
        DEBUG_SERVICE_EXECUTING = DEBUG_ALL;
        DEBUG_STACK = DEBUG_ALL;
        DEBUG_STATES = DEBUG_ALL_ACTIVITIES;
        DEBUG_SWITCH = DEBUG_ALL;
        DEBUG_TASKS = DEBUG_ALL;
        DEBUG_THUMBNAILS = DEBUG_ALL;
        DEBUG_TRANSITION = DEBUG_ALL;
        DEBUG_UID_OBSERVERS = DEBUG_ALL;
        DEBUG_URI_PERMISSION = DEBUG_ALL;
        DEBUG_USER_LEAVING = DEBUG_ALL;
        DEBUG_VISIBILITY = DEBUG_ALL;
        DEBUG_VISIBLE_BEHIND = DEBUG_ALL_ACTIVITIES;
        DEBUG_USAGE_STATS = DEBUG_ALL;
        DEBUG_PERMISSIONS_REVIEW = DEBUG_ALL;
        DEBUG_WHITELISTS = DEBUG_ALL;
        DEBUG_PERMISSION = DEBUG_ALL;
        DEBUG_TASK_RETURNTO = DEBUG_ALL;
        DEBUG_MULTIWINDOW = DEBUG_ALL;
        POSTFIX_ADD_REMOVE = "";
        POSTFIX_APP = "";
        POSTFIX_BACKUP = "";
        POSTFIX_BROADCAST = "";
        POSTFIX_CLEANUP = "";
        POSTFIX_CONFIGURATION = "";
        POSTFIX_CONTAINERS = "";
        POSTFIX_FOCUS = "";
        POSTFIX_IDLE = "";
        POSTFIX_IMMERSIVE = "";
        POSTFIX_LOCKSCREEN = "";
        POSTFIX_LOCKTASK = "";
        POSTFIX_LRU = "";
        POSTFIX_OOM_ADJ = "";
        POSTFIX_PAUSE = "";
        POSTFIX_POWER = "";
        POSTFIX_PROCESS_OBSERVERS = "";
        POSTFIX_PROCESSES = "";
        POSTFIX_PROVIDER = "";
        POSTFIX_PSS = "";
        POSTFIX_RECENTS = "";
        POSTFIX_RELEASE = "";
        POSTFIX_RESULTS = "";
        POSTFIX_SAVED_STATE = "";
        POSTFIX_SCREENSHOTS = "";
        POSTFIX_SERVICE = "";
        POSTFIX_SERVICE_EXECUTING = "";
        POSTFIX_STACK = "";
        POSTFIX_STATES = "";
        POSTFIX_SWITCH = "";
        POSTFIX_TASKS = "";
        POSTFIX_THUMBNAILS = "";
        POSTFIX_TRANSITION = "";
        POSTFIX_UID_OBSERVERS = "";
        POSTFIX_URI_PERMISSION = "";
        POSTFIX_USER_LEAVING = "";
        POSTFIX_VISIBILITY = "";
        POSTFIX_VISIBLE_BEHIND = "";
    }
}
