package org.apache.xalan.processor;

import java.util.HashMap;
import org.apache.xalan.templates.Constants;
import org.apache.xalan.templates.ElemApplyImport;
import org.apache.xalan.templates.ElemApplyTemplates;
import org.apache.xalan.templates.ElemAttribute;
import org.apache.xalan.templates.ElemCallTemplate;
import org.apache.xalan.templates.ElemChoose;
import org.apache.xalan.templates.ElemComment;
import org.apache.xalan.templates.ElemCopy;
import org.apache.xalan.templates.ElemCopyOf;
import org.apache.xalan.templates.ElemElement;
import org.apache.xalan.templates.ElemExsltFuncResult;
import org.apache.xalan.templates.ElemExsltFunction;
import org.apache.xalan.templates.ElemExtensionDecl;
import org.apache.xalan.templates.ElemExtensionScript;
import org.apache.xalan.templates.ElemFallback;
import org.apache.xalan.templates.ElemForEach;
import org.apache.xalan.templates.ElemIf;
import org.apache.xalan.templates.ElemLiteralResult;
import org.apache.xalan.templates.ElemMessage;
import org.apache.xalan.templates.ElemNumber;
import org.apache.xalan.templates.ElemOtherwise;
import org.apache.xalan.templates.ElemPI;
import org.apache.xalan.templates.ElemParam;
import org.apache.xalan.templates.ElemSort;
import org.apache.xalan.templates.ElemTemplate;
import org.apache.xalan.templates.ElemText;
import org.apache.xalan.templates.ElemTextLiteral;
import org.apache.xalan.templates.ElemUnknown;
import org.apache.xalan.templates.ElemValueOf;
import org.apache.xalan.templates.ElemVariable;
import org.apache.xalan.templates.ElemWhen;
import org.apache.xalan.templates.ElemWithParam;
import org.apache.xml.utils.QName;

public class XSLTSchema extends XSLTElementDef {
    private HashMap m_availElems = new HashMap();

    XSLTSchema() {
        build();
    }

    void build() {
        XSLTAttributeDef hrefAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_HREF, 2, true, false, 1);
        XSLTAttributeDef elementsAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_ELEMENTS, 12, true, false, 1);
        XSLTAttributeDef methodAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_OUTPUT_METHOD, 9, false, false, 1);
        XSLTAttributeDef versionAttr = new XSLTAttributeDef((String) null, "version", 13, false, false, 1);
        XSLTAttributeDef encodingAttr = new XSLTAttributeDef((String) null, "encoding", 1, false, false, 1);
        XSLTAttributeDef omitXmlDeclarationAttr = new XSLTAttributeDef((String) null, "omit-xml-declaration", 8, false, false, 1);
        XSLTAttributeDef standaloneAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_OUTPUT_STANDALONE, 8, false, false, 1);
        XSLTAttributeDef doctypePublicAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_OUTPUT_DOCTYPE_PUBLIC, 1, false, false, 1);
        XSLTAttributeDef doctypeSystemAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_OUTPUT_DOCTYPE_SYSTEM, 1, false, false, 1);
        XSLTAttributeDef cdataSectionElementsAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_OUTPUT_CDATA_SECTION_ELEMENTS, 19, false, false, 1);
        XSLTAttributeDef indentAttr = new XSLTAttributeDef((String) null, "indent", 8, false, false, 1);
        XSLTAttributeDef mediaTypeAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_OUTPUT_MEDIATYPE, 1, false, false, 1);
        XSLTAttributeDef nameAttrRequired = new XSLTAttributeDef((String) null, "name", 9, true, false, 1);
        XSLTAttributeDef nameAVTRequired = new XSLTAttributeDef((String) null, "name", 18, true, true, 2);
        XSLTAttributeDef nameAVT_NCNAMERequired = new XSLTAttributeDef((String) null, "name", 17, true, true, 2);
        XSLTAttributeDef nameAttrOpt_ERROR = new XSLTAttributeDef((String) null, "name", 9, false, false, 1);
        XSLTAttributeDef useAttr = new XSLTAttributeDef((String) null, "use", 5, true, false, 1);
        XSLTAttributeDef namespaceAVTOpt = new XSLTAttributeDef((String) null, Constants.ATTRNAME_NAMESPACE, 2, false, true, 2);
        XSLTAttributeDef decimalSeparatorAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_DECIMALSEPARATOR, 6, false, 1, Constants.ATTRVAL_THIS);
        XSLTAttributeDef infinityAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_INFINITY, 1, false, 1, Constants.ATTRVAL_INFINITY);
        XSLTAttributeDef minusSignAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_MINUSSIGN, 6, false, 1, "-");
        XSLTAttributeDef NaNAttr = new XSLTAttributeDef((String) null, "NaN", 1, false, 1, "NaN");
        XSLTAttributeDef percentAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_PERCENT, 6, false, 1, "%");
        XSLTAttributeDef perMilleAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_PERMILLE, 6, false, false, 1);
        XSLTAttributeDef zeroDigitAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_ZERODIGIT, 6, false, 1, "0");
        XSLTAttributeDef digitAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_DIGIT, 6, false, 1, "#");
        XSLTAttributeDef patternSeparatorAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_PATTERNSEPARATOR, 6, false, 1, ";");
        XSLTAttributeDef groupingSeparatorAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_GROUPINGSEPARATOR, 6, false, 1, ",");
        XSLTAttributeDef useAttributeSetsAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_USEATTRIBUTESETS, 10, false, false, 1);
        XSLTAttributeDef testAttrRequired = new XSLTAttributeDef((String) null, Constants.ATTRNAME_TEST, 5, true, false, 1);
        XSLTAttributeDef selectAttrRequired = new XSLTAttributeDef((String) null, Constants.ATTRNAME_SELECT, 5, true, false, 1);
        XSLTAttributeDef selectAttrOpt = new XSLTAttributeDef((String) null, Constants.ATTRNAME_SELECT, 5, false, false, 1);
        XSLTAttributeDef selectAttrDefNode = new XSLTAttributeDef((String) null, Constants.ATTRNAME_SELECT, 5, false, 1, "node()");
        XSLTAttributeDef selectAttrDefDot = new XSLTAttributeDef((String) null, Constants.ATTRNAME_SELECT, 5, false, 1, Constants.ATTRVAL_THIS);
        XSLTAttributeDef matchAttrRequired = new XSLTAttributeDef((String) null, Constants.ATTRNAME_MATCH, 4, true, false, 1);
        XSLTAttributeDef matchAttrOpt = new XSLTAttributeDef((String) null, Constants.ATTRNAME_MATCH, 4, false, false, 1);
        XSLTAttributeDef priorityAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_PRIORITY, 7, false, false, 1);
        XSLTAttributeDef modeAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_MODE, 9, false, false, 1);
        XSLTAttributeDef spaceAttr = new XSLTAttributeDef("http://www.w3.org/XML/1998/namespace", "space", false, false, false, 2, Constants.ATTRNAME_DEFAULT, 2, "preserve", 1);
        XSLTAttributeDef spaceAttrLiteral = new XSLTAttributeDef("http://www.w3.org/XML/1998/namespace", "space", 2, false, true, 1);
        XSLTAttributeDef stylesheetPrefixAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_STYLESHEET_PREFIX, 1, true, false, 1);
        XSLTAttributeDef resultPrefixAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_RESULT_PREFIX, 1, true, false, 1);
        XSLTAttributeDef disableOutputEscapingAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_DISABLE_OUTPUT_ESCAPING, 8, false, false, 1);
        XSLTAttributeDef levelAttr = new XSLTAttributeDef(null, Constants.ATTRNAME_LEVEL, false, false, false, 1, Constants.ATTRVAL_SINGLE, 1, Constants.ATTRVAL_MULTI, 2, "any", 3);
        levelAttr.setDefault(Constants.ATTRVAL_SINGLE);
        XSLTAttributeDef countAttr = new XSLTAttributeDef((String) null, "count", 4, false, false, 1);
        XSLTAttributeDef fromAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_FROM, 4, false, false, 1);
        XSLTAttributeDef valueAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_VALUE, 5, false, false, 1);
        XSLTAttributeDef formatAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_FORMAT, 1, false, true, 1);
        formatAttr.setDefault("1");
        XSLTAttributeDef langAttr = new XSLTAttributeDef((String) null, "lang", 13, false, true, 1);
        XSLTAttributeDef letterValueAttr = new XSLTAttributeDef(null, Constants.ATTRNAME_LETTERVALUE, false, true, false, 1, Constants.ATTRVAL_ALPHABETIC, 1, Constants.ATTRVAL_TRADITIONAL, 2);
        XSLTAttributeDef groupingSeparatorAVT = new XSLTAttributeDef((String) null, Constants.ATTRNAME_GROUPINGSEPARATOR, 6, false, true, 1);
        XSLTAttributeDef groupingSizeAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_GROUPINGSIZE, 7, false, true, 1);
        XSLTAttributeDef dataTypeAttr = new XSLTAttributeDef(null, Constants.ATTRNAME_DATATYPE, false, true, true, 1, "text", 1, "number", 1);
        dataTypeAttr.setDefault("text");
        XSLTAttributeDef orderAttr = new XSLTAttributeDef(null, Constants.ATTRNAME_ORDER, false, true, false, 1, Constants.ATTRVAL_ORDER_ASCENDING, 1, Constants.ATTRVAL_ORDER_DESCENDING, 2);
        orderAttr.setDefault(Constants.ATTRVAL_ORDER_ASCENDING);
        XSLTAttributeDef caseOrderAttr = new XSLTAttributeDef(null, Constants.ATTRNAME_CASEORDER, false, true, false, 1, Constants.ATTRVAL_CASEORDER_UPPER, 1, Constants.ATTRVAL_CASEORDER_LOWER, 2);
        XSLTAttributeDef terminateAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_TERMINATE, 8, false, false, 1);
        terminateAttr.setDefault("no");
        XSLTAttributeDef xslExcludeResultPrefixesAttr = new XSLTAttributeDef(org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ATTRNAME_EXCLUDE_RESULT_PREFIXES, 20, false, false, 1);
        XSLTAttributeDef xslExtensionElementPrefixesAttr = new XSLTAttributeDef(org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ATTRNAME_EXTENSIONELEMENTPREFIXES, 15, false, false, 1);
        XSLTAttributeDef xslUseAttributeSetsAttr = new XSLTAttributeDef(org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ATTRNAME_USEATTRIBUTESETS, 10, false, false, 1);
        XSLTAttributeDef xslVersionAttr = new XSLTAttributeDef(org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, "version", 13, false, false, 1);
        XSLTElementDef charData = new XSLTElementDef(this, null, "text()", null, null, null, new ProcessorCharacters(), ElemTextLiteral.class);
        charData.setType(2);
        XSLTElementDef whiteSpaceOnly = new XSLTElementDef(this, null, "text()", null, null, null, null, ElemTextLiteral.class);
        charData.setType(2);
        XSLTAttributeDef resultAttr = new XSLTAttributeDef((String) null, "*", 3, false, true, 2);
        XSLTAttributeDef xslResultAttr = new XSLTAttributeDef(org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, "*", 1, false, false, 2);
        XSLTElementDef[] templateElements = new XSLTElementDef[23];
        XSLTElementDef[] templateElementsAndParams = new XSLTElementDef[24];
        XSLTElementDef[] templateElementsAndSort = new XSLTElementDef[24];
        XSLTElementDef[] exsltFunctionElements = new XSLTElementDef[24];
        XSLTElementDef[] charTemplateElements = new XSLTElementDef[15];
        XSLTElementDef resultElement = new XSLTElementDef(this, (String) null, "*", (String) null, templateElements, new XSLTAttributeDef[]{spaceAttrLiteral, xslExcludeResultPrefixesAttr, xslExtensionElementPrefixesAttr, xslUseAttributeSetsAttr, xslVersionAttr, xslResultAttr, resultAttr}, (XSLTElementProcessor) new ProcessorLRE(), ElemLiteralResult.class, 20, true);
        XSLTElementDef unknownElement = new XSLTElementDef(this, "*", "unknown", (String) null, templateElementsAndParams, new XSLTAttributeDef[]{xslExcludeResultPrefixesAttr, xslExtensionElementPrefixesAttr, xslUseAttributeSetsAttr, xslVersionAttr, xslResultAttr, resultAttr}, (XSLTElementProcessor) new ProcessorUnknown(), ElemUnknown.class, 20, true);
        XSLTElementDef xslValueOf = new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_VALUEOF_STRING, (String) null, (XSLTElementDef[]) null, new XSLTAttributeDef[]{selectAttrRequired, disableOutputEscapingAttr}, (XSLTElementProcessor) new ProcessorTemplateElem(), ElemValueOf.class, 20, true);
        XSLTElementDef xslCopyOf = new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_COPY_OF_STRING, (String) null, (XSLTElementDef[]) null, new XSLTAttributeDef[]{selectAttrRequired}, (XSLTElementProcessor) new ProcessorTemplateElem(), ElemCopyOf.class, 20, true);
        XSLTElementDef xslNumber = new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, "number", (String) null, (XSLTElementDef[]) null, new XSLTAttributeDef[]{levelAttr, countAttr, fromAttr, valueAttr, formatAttr, langAttr, letterValueAttr, groupingSeparatorAVT, groupingSizeAttr}, (XSLTElementProcessor) new ProcessorTemplateElem(), ElemNumber.class, 20, true);
        XSLTElementDef xslSort = new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_SORT_STRING, (String) null, (XSLTElementDef[]) null, new XSLTAttributeDef[]{selectAttrDefDot, langAttr, dataTypeAttr, orderAttr, caseOrderAttr}, (XSLTElementProcessor) new ProcessorTemplateElem(), ElemSort.class, 19, true);
        XSLTElementDef xslWithParam = new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_WITHPARAM_STRING, (String) null, templateElements, new XSLTAttributeDef[]{nameAttrRequired, selectAttrOpt}, (XSLTElementProcessor) new ProcessorTemplateElem(), ElemWithParam.class, 19, true);
        XSLTElementDef xslApplyTemplates = new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_APPLY_TEMPLATES_STRING, (String) null, new XSLTElementDef[]{xslSort, xslWithParam}, new XSLTAttributeDef[]{selectAttrDefNode, modeAttr}, (XSLTElementProcessor) new ProcessorTemplateElem(), ElemApplyTemplates.class, 20, true);
        XSLTElementDef xslApplyImports = new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_APPLY_IMPORTS_STRING, null, null, new XSLTAttributeDef[0], new ProcessorTemplateElem(), ElemApplyImport.class);
        XSLTElementDef xslForEach = new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_FOREACH_STRING, null, templateElementsAndSort, new XSLTAttributeDef[]{selectAttrRequired, spaceAttr}, new ProcessorTemplateElem(), ElemForEach.class, true, false, true, 20, true);
        XSLTElementDef xslIf = new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_IF_STRING, (String) null, templateElements, new XSLTAttributeDef[]{testAttrRequired, spaceAttr}, (XSLTElementProcessor) new ProcessorTemplateElem(), ElemIf.class, 20, true);
        XSLTElementDef xslWhen = new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_WHEN_STRING, null, templateElements, new XSLTAttributeDef[]{testAttrRequired, spaceAttr}, new ProcessorTemplateElem(), ElemWhen.class, false, true, 1, true);
        XSLTElementDef xslOtherwise = new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_OTHERWISE_STRING, null, templateElements, new XSLTAttributeDef[]{spaceAttr}, new ProcessorTemplateElem(), ElemOtherwise.class, false, false, 2, false);
        XSLTElementDef xslChoose = new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_CHOOSE_STRING, null, new XSLTElementDef[]{xslWhen, xslOtherwise}, new XSLTAttributeDef[]{spaceAttr}, new ProcessorTemplateElem(), ElemChoose.class, true, false, true, 20, true);
        XSLTElementDef xslAttribute = new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, "attribute", (String) null, charTemplateElements, new XSLTAttributeDef[]{nameAVTRequired, namespaceAVTOpt, spaceAttr}, (XSLTElementProcessor) new ProcessorTemplateElem(), ElemAttribute.class, 20, true);
        XSLTElementDef xslCallTemplate = new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_CALLTEMPLATE_STRING, (String) null, new XSLTElementDef[]{xslWithParam}, new XSLTAttributeDef[]{nameAttrRequired}, (XSLTElementProcessor) new ProcessorTemplateElem(), ElemCallTemplate.class, 20, true);
        XSLTElementDef xslVariable = new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_VARIABLE_STRING, (String) null, templateElements, new XSLTAttributeDef[]{nameAttrRequired, selectAttrOpt}, (XSLTElementProcessor) new ProcessorTemplateElem(), ElemVariable.class, 20, true);
        XSLTElementDef xslParam = new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_PARAMVARIABLE_STRING, (String) null, templateElements, new XSLTAttributeDef[]{nameAttrRequired, selectAttrOpt}, (XSLTElementProcessor) new ProcessorTemplateElem(), ElemParam.class, 19, true);
        XSLTElementDef xslText = new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, "text", (String) null, new XSLTElementDef[]{charData}, new XSLTAttributeDef[]{disableOutputEscapingAttr}, (XSLTElementProcessor) new ProcessorText(), ElemText.class, 20, true);
        XSLTElementDef xslProcessingInstruction = new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_PI_STRING, (String) null, charTemplateElements, new XSLTAttributeDef[]{nameAVT_NCNAMERequired, spaceAttr}, (XSLTElementProcessor) new ProcessorTemplateElem(), ElemPI.class, 20, true);
        XSLTElementDef xslElement = new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, "element", (String) null, templateElements, new XSLTAttributeDef[]{nameAVTRequired, namespaceAVTOpt, useAttributeSetsAttr, spaceAttr}, (XSLTElementProcessor) new ProcessorTemplateElem(), ElemElement.class, 20, true);
        XSLTElementDef xslComment = new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_COMMENT_STRING, (String) null, charTemplateElements, new XSLTAttributeDef[]{spaceAttr}, (XSLTElementProcessor) new ProcessorTemplateElem(), ElemComment.class, 20, true);
        XSLTElementDef xslCopy = new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_COPY_STRING, (String) null, templateElements, new XSLTAttributeDef[]{spaceAttr, useAttributeSetsAttr}, (XSLTElementProcessor) new ProcessorTemplateElem(), ElemCopy.class, 20, true);
        XSLTElementDef xslMessage = new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_MESSAGE_STRING, (String) null, templateElements, new XSLTAttributeDef[]{terminateAttr}, (XSLTElementProcessor) new ProcessorTemplateElem(), ElemMessage.class, 20, true);
        XSLTElementDef xslFallback = new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_FALLBACK_STRING, (String) null, templateElements, new XSLTAttributeDef[]{spaceAttr}, (XSLTElementProcessor) new ProcessorTemplateElem(), ElemFallback.class, 20, true);
        XSLTElementDef exsltFunction = new XSLTElementDef(this, org.apache.xml.utils.Constants.S_EXSLT_FUNCTIONS_URL, Constants.EXSLT_ELEMNAME_FUNCTION_STRING, null, exsltFunctionElements, new XSLTAttributeDef[]{nameAttrRequired}, new ProcessorExsltFunction(), ElemExsltFunction.class);
        XSLTElementDef exsltResult = new XSLTElementDef(this, org.apache.xml.utils.Constants.S_EXSLT_FUNCTIONS_URL, Constants.EXSLT_ELEMNAME_FUNCRESULT_STRING, null, templateElements, new XSLTAttributeDef[]{selectAttrOpt}, new ProcessorExsltFuncResult(), ElemExsltFuncResult.class);
        int i = 0 + 1;
        templateElements[0] = charData;
        int i2 = i + 1;
        templateElements[i] = xslApplyTemplates;
        int i3 = i2 + 1;
        templateElements[i2] = xslCallTemplate;
        int i4 = i3 + 1;
        templateElements[i3] = xslApplyImports;
        int i5 = i4 + 1;
        templateElements[i4] = xslForEach;
        int i6 = i5 + 1;
        templateElements[i5] = xslValueOf;
        int i7 = i6 + 1;
        templateElements[i6] = xslCopyOf;
        int i8 = i7 + 1;
        templateElements[i7] = xslNumber;
        int i9 = i8 + 1;
        templateElements[i8] = xslChoose;
        int i10 = i9 + 1;
        templateElements[i9] = xslIf;
        int i11 = i10 + 1;
        templateElements[i10] = xslText;
        int i12 = i11 + 1;
        templateElements[i11] = xslCopy;
        int i13 = i12 + 1;
        templateElements[i12] = xslVariable;
        int i14 = i13 + 1;
        templateElements[i13] = xslMessage;
        int i15 = i14 + 1;
        templateElements[i14] = xslFallback;
        int i16 = i15 + 1;
        templateElements[i15] = xslProcessingInstruction;
        int i17 = i16 + 1;
        templateElements[i16] = xslComment;
        int i18 = i17 + 1;
        templateElements[i17] = xslElement;
        int i19 = i18 + 1;
        templateElements[i18] = xslAttribute;
        int i20 = i19 + 1;
        templateElements[i19] = resultElement;
        int i21 = i20 + 1;
        templateElements[i20] = unknownElement;
        int i22 = i21 + 1;
        templateElements[i21] = exsltFunction;
        int i23 = i22 + 1;
        templateElements[i22] = exsltResult;
        System.arraycopy(templateElements, 0, templateElementsAndParams, 0, i23);
        System.arraycopy(templateElements, 0, templateElementsAndSort, 0, i23);
        System.arraycopy(templateElements, 0, exsltFunctionElements, 0, i23);
        templateElementsAndParams[i23] = xslParam;
        templateElementsAndSort[i23] = xslSort;
        exsltFunctionElements[i23] = xslParam;
        int i24 = 0 + 1;
        charTemplateElements[0] = charData;
        int i25 = i24 + 1;
        charTemplateElements[i24] = xslApplyTemplates;
        int i26 = i25 + 1;
        charTemplateElements[i25] = xslCallTemplate;
        int i27 = i26 + 1;
        charTemplateElements[i26] = xslApplyImports;
        int i28 = i27 + 1;
        charTemplateElements[i27] = xslForEach;
        int i29 = i28 + 1;
        charTemplateElements[i28] = xslValueOf;
        int i30 = i29 + 1;
        charTemplateElements[i29] = xslCopyOf;
        int i31 = i30 + 1;
        charTemplateElements[i30] = xslNumber;
        int i32 = i31 + 1;
        charTemplateElements[i31] = xslChoose;
        int i33 = i32 + 1;
        charTemplateElements[i32] = xslIf;
        int i34 = i33 + 1;
        charTemplateElements[i33] = xslText;
        int i35 = i34 + 1;
        charTemplateElements[i34] = xslCopy;
        int i36 = i35 + 1;
        charTemplateElements[i35] = xslVariable;
        int i37 = i36 + 1;
        charTemplateElements[i36] = xslMessage;
        int i38 = i37 + 1;
        charTemplateElements[i37] = xslFallback;
        XSLTElementDef importDef = new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_IMPORT_STRING, (String) null, (XSLTElementDef[]) null, new XSLTAttributeDef[]{hrefAttr}, (XSLTElementProcessor) new ProcessorImport(), (Class) null, 1, true);
        XSLTElementDef includeDef = new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_INCLUDE_STRING, (String) null, (XSLTElementDef[]) null, new XSLTAttributeDef[]{hrefAttr}, (XSLTElementProcessor) new ProcessorInclude(), (Class) null, 20, true);
        XSLTAttributeDef[] scriptAttrs = {new XSLTAttributeDef((String) null, "lang", 13, true, false, 2), new XSLTAttributeDef((String) null, "src", 2, false, false, 2)};
        XSLTAttributeDef[] componentAttrs = {new XSLTAttributeDef((String) null, "prefix", 13, true, false, 2), new XSLTAttributeDef((String) null, Constants.ATTRNAME_ELEMENTS, 14, false, false, 2), new XSLTAttributeDef((String) null, Constants.ELEMNAME_EXTENSION_STRING, 14, false, false, 2)};
        XSLTElementDef[] topLevelElements = {includeDef, importDef, whiteSpaceOnly, unknownElement, new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_STRIPSPACE_STRING, (String) null, (XSLTElementDef[]) null, new XSLTAttributeDef[]{elementsAttr}, (XSLTElementProcessor) new ProcessorStripSpace(), (Class) null, 20, true), new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_PRESERVESPACE_STRING, (String) null, (XSLTElementDef[]) null, new XSLTAttributeDef[]{elementsAttr}, (XSLTElementProcessor) new ProcessorPreserveSpace(), (Class) null, 20, true), new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_OUTPUT_STRING, (String) null, (XSLTElementDef[]) null, new XSLTAttributeDef[]{methodAttr, versionAttr, encodingAttr, omitXmlDeclarationAttr, standaloneAttr, doctypePublicAttr, doctypeSystemAttr, cdataSectionElementsAttr, indentAttr, mediaTypeAttr, XSLTAttributeDef.m_foreignAttr}, (XSLTElementProcessor) new ProcessorOutputElem(), (Class) null, 20, true), new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, "key", (String) null, (XSLTElementDef[]) null, new XSLTAttributeDef[]{nameAttrRequired, matchAttrRequired, useAttr}, (XSLTElementProcessor) new ProcessorKey(), (Class) null, 20, true), new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_DECIMALFORMAT_STRING, (String) null, (XSLTElementDef[]) null, new XSLTAttributeDef[]{nameAttrOpt_ERROR, decimalSeparatorAttr, groupingSeparatorAttr, infinityAttr, minusSignAttr, NaNAttr, percentAttr, perMilleAttr, zeroDigitAttr, digitAttr, patternSeparatorAttr}, (XSLTElementProcessor) new ProcessorDecimalFormat(), (Class) null, 20, true), new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, "attribute-set", (String) null, new XSLTElementDef[]{xslAttribute}, new XSLTAttributeDef[]{nameAttrRequired, useAttributeSetsAttr}, (XSLTElementProcessor) new ProcessorAttributeSet(), (Class) null, 20, true), new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_VARIABLE_STRING, (String) null, templateElements, new XSLTAttributeDef[]{nameAttrRequired, selectAttrOpt}, (XSLTElementProcessor) new ProcessorGlobalVariableDecl(), ElemVariable.class, 20, true), new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_PARAMVARIABLE_STRING, (String) null, templateElements, new XSLTAttributeDef[]{nameAttrRequired, selectAttrOpt}, (XSLTElementProcessor) new ProcessorGlobalParamDecl(), ElemParam.class, 20, true), new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_TEMPLATE_STRING, null, templateElementsAndParams, new XSLTAttributeDef[]{matchAttrOpt, nameAttrOpt_ERROR, priorityAttr, modeAttr, spaceAttr}, new ProcessorTemplate(), ElemTemplate.class, true, 20, true), new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_NSALIAS_STRING, (String) null, (XSLTElementDef[]) null, new XSLTAttributeDef[]{stylesheetPrefixAttr, resultPrefixAttr}, (XSLTElementProcessor) new ProcessorNamespaceAlias(), (Class) null, 20, true), new XSLTElementDef(this, "http://xml.apache.org/xalan", Constants.ELEMNAME_COMPONENT_STRING, null, new XSLTElementDef[]{new XSLTElementDef(this, "http://xml.apache.org/xalan", Constants.ELEMNAME_SCRIPT_STRING, (String) null, new XSLTElementDef[]{charData}, scriptAttrs, (XSLTElementProcessor) new ProcessorLRE(), ElemExtensionScript.class, 20, true)}, componentAttrs, new ProcessorLRE(), ElemExtensionDecl.class), new XSLTElementDef(this, org.apache.xml.utils.Constants.S_BUILTIN_OLD_EXTENSIONS_URL, Constants.ELEMNAME_COMPONENT_STRING, null, new XSLTElementDef[]{new XSLTElementDef(this, org.apache.xml.utils.Constants.S_BUILTIN_OLD_EXTENSIONS_URL, Constants.ELEMNAME_SCRIPT_STRING, (String) null, new XSLTElementDef[]{charData}, scriptAttrs, (XSLTElementProcessor) new ProcessorLRE(), ElemExtensionScript.class, 20, true)}, componentAttrs, new ProcessorLRE(), ElemExtensionDecl.class), exsltFunction};
        XSLTAttributeDef excludeResultPrefixesAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_EXCLUDE_RESULT_PREFIXES, 20, false, false, 2);
        XSLTAttributeDef extensionElementPrefixesAttr = new XSLTAttributeDef((String) null, Constants.ATTRNAME_EXTENSIONELEMENTPREFIXES, 15, false, false, 2);
        XSLTAttributeDef idAttr = new XSLTAttributeDef((String) null, "id", 1, false, false, 2);
        XSLTAttributeDef versionAttrRequired = new XSLTAttributeDef((String) null, "version", 13, true, false, 2);
        XSLTElementDef stylesheetElemDef = new XSLTElementDef(this, org.apache.xml.utils.Constants.S_XSLNAMESPACEURL, Constants.ELEMNAME_STYLESHEET_STRING, Constants.ELEMNAME_TRANSFORM_STRING, topLevelElements, new XSLTAttributeDef[]{extensionElementPrefixesAttr, excludeResultPrefixesAttr, idAttr, versionAttrRequired, spaceAttr}, new ProcessorStylesheetElement(), null, true, -1, false);
        importDef.setElements(new XSLTElementDef[]{stylesheetElemDef, resultElement, unknownElement});
        includeDef.setElements(new XSLTElementDef[]{stylesheetElemDef, resultElement, unknownElement});
        build(null, null, null, new XSLTElementDef[]{stylesheetElemDef, whiteSpaceOnly, resultElement, unknownElement}, null, new ProcessorStylesheetDoc(), null);
    }

    public HashMap getElemsAvailable() {
        return this.m_availElems;
    }

    void addAvailableElement(QName elemName) {
        this.m_availElems.put(elemName, elemName);
    }

    public boolean elementAvailable(QName elemName) {
        return this.m_availElems.containsKey(elemName);
    }
}
