jadx.core.utils.exceptions.JadxRuntimeException: Failed to generate code for class: com.android.server.am.ActivityManagerService
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:132)
	at jadx.core.dex.nodes.ClassNode.generateClassCode(ClassNode.java:405)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:393)
	at jadx.core.dex.nodes.ClassNode.getCode(ClassNode.java:343)
Caused by: jadx.core.utils.exceptions.JadxRuntimeException: Code generation error after restart
	at jadx.core.codegen.CodeGen.wrapCodeGen(CodeGen.java:52)
	at jadx.core.codegen.CodeGen.generateJavaCode(CodeGen.java:34)
	at jadx.core.codegen.CodeGen.generate(CodeGen.java:22)
	at jadx.core.ProcessClass.process(ProcessClass.java:88)
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:126)
	... 3 more
Caused by: jadx.core.utils.exceptions.JadxRuntimeException: Method generation error
	at jadx.core.codegen.ClassGen.addMethod(ClassGen.java:340)
	at jadx.core.codegen.ClassGen.lambda$addInnerClsAndMethods$3(ClassGen.java:303)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:186)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:261)
	at java.base/java.util.stream.ReferencePipeline$7$1FlatMap.end(ReferencePipeline.java:284)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:571)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:153)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:176)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:632)
	at jadx.core.codegen.ClassGen.addInnerClsAndMethods(ClassGen.java:299)
	at jadx.core.codegen.ClassGen.addClassBody(ClassGen.java:288)
	at jadx.core.codegen.ClassGen.addClassBody(ClassGen.java:272)
	at jadx.core.codegen.ClassGen.addClassCode(ClassGen.java:159)
	at jadx.core.codegen.ClassGen.makeClass(ClassGen.java:103)
	at jadx.core.codegen.CodeGen.wrapCodeGen(CodeGen.java:50)
	... 7 more
Caused by: jadx.core.utils.exceptions.CodegenException: Error generate insn: 0x0221: MOVE_EXCEPTION (r4v15 'th' java.lang.Throwable A[CUSTOM_DECLARE]) =  A[DONT_INLINE, ExcHandler: all -> 0x0221] (LINE:11369) in method: com.android.server.am.ActivityManagerService.systemReady(java.lang.Runnable):void, file: classes.dex
	at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:310)
	at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:273)
	at jadx.core.codegen.RegionGen.makeSimpleBlock(RegionGen.java:94)
	at jadx.core.dex.nodes.IBlock.generate(IBlock.java:15)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:66)
	at jadx.core.dex.regions.Region.generate(Region.java:35)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:66)
	at jadx.core.dex.regions.Region.generate(Region.java:35)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:66)
	at jadx.core.codegen.RegionGen.makeRegionIndent(RegionGen.java:83)
	at jadx.core.codegen.RegionGen.makeSynchronizedRegion(RegionGen.java:240)
	at jadx.core.dex.regions.SynchronizedRegion.generate(SynchronizedRegion.java:44)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:66)
	at jadx.core.dex.regions.Region.generate(Region.java:35)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:66)
	at jadx.core.dex.regions.Region.generate(Region.java:35)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:66)
	at jadx.core.codegen.RegionGen.makeRegionIndent(RegionGen.java:83)
	at jadx.core.codegen.RegionGen.makeSynchronizedRegion(RegionGen.java:240)
	at jadx.core.dex.regions.SynchronizedRegion.generate(SynchronizedRegion.java:44)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:66)
	at jadx.core.dex.regions.Region.generate(Region.java:35)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:66)
	at jadx.core.codegen.RegionGen.makeRegionIndent(RegionGen.java:83)
	at jadx.core.codegen.RegionGen.makeIf(RegionGen.java:140)
	at jadx.core.dex.regions.conditions.IfRegion.generate(IfRegion.java:90)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:66)
	at jadx.core.dex.regions.Region.generate(Region.java:35)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:66)
	at jadx.core.dex.regions.Region.generate(Region.java:35)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:66)
	at jadx.core.codegen.RegionGen.makeRegionIndent(RegionGen.java:83)
	at jadx.core.codegen.RegionGen.makeSynchronizedRegion(RegionGen.java:240)
	at jadx.core.dex.regions.SynchronizedRegion.generate(SynchronizedRegion.java:44)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:66)
	at jadx.core.dex.regions.Region.generate(Region.java:35)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:66)
	at jadx.core.codegen.MethodGen.addRegionInsns(MethodGen.java:305)
	at jadx.core.codegen.MethodGen.addInstructions(MethodGen.java:289)
	at jadx.core.codegen.ClassGen.addMethodCode(ClassGen.java:412)
	at jadx.core.codegen.ClassGen.addMethod(ClassGen.java:337)
	... 25 more
Caused by: jadx.core.utils.exceptions.CodegenException: MOVE_EXCEPTION instruction can be used only in fallback mode
	at jadx.core.codegen.InsnGen.fallbackOnlyInsn(InsnGen.java:698)
	at jadx.core.codegen.InsnGen.makeInsnBody(InsnGen.java:561)
	at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:303)
	... 65 more

